---
script:
  - id: preview_rfid_data
    then:
      - text_sensor.template.publish:
          id: nfc_preview
          state: !lambda "id(filament_color_hexaa).publish_state(id(filament_color_hex).state + id(filament_alpha).state);\nauto pretty_json = [=]() -> std::string {\n  JsonDocument doc;\n  JsonObject root = doc.to<JsonObject>();\n  #magic___^_^___line\n  root[\"protocol\"] = \"openspool\";\n  root[\"version\"] = \"1.0\";\n  root[\"brand\"] = id(filament_brand).state.c_str();\n  if (id(filament_include_alpha).state == true){\n    root[\"color_hex\"] = id(filament_color_hexaa).state.c_str();   \n  }\n  else{\n    root[\"color_hex\"] = id(filament_color_hex).state.c_str();\n  } \n  root[\"min_temp\"] = id(filament_min_temp).state;\n  root[\"max_temp\"] = id(filament_max_temp).state;\n  root[\"type\"] = id(filament_type).state.c_str();\n    #magic___^_^___line\n  std::string output;\n  serializeJsonPretty(doc, output);\n  return output;\n};\nreturn pretty_json();"
  - id: publish_filament_setting
    then:
      - if:
          condition:
            and:
              - lambda: |-
                  if (id(filament_brand).state == "" || id(filament_brand).state == "Unknown") {
                    ESP_LOGE("main", "Filament Brand cannot be empty");
                    return false;
                  } else {
                    return true;
                  }
              - lambda: |-
                  if (id(filament_brand_code).state == "" || id(filament_brand_code).state == "Unknown") {
                    ESP_LOGE("main", "Filament Brand Code cannot be empty");
                    return false;
                  } else {
                    return true;
                  }
              - lambda: |-
                  if (id(filament_color_hex).state == "") {
                    ESP_LOGE("main", "Filament Color Hex cannot be empty");
                    return false;
                  } else {
                    return true;
                  }
              - lambda: |-
                  if (id(filament_max_temp).state >= 300) {
                    ESP_LOGE("main", "Filament Min Temp must be less than 300");
                    return false;
                  } else {
                    return true;
                  }
              - lambda: |-
                  if (id(filament_min_temp).state <= 150) {
                    ESP_LOGE("main", "Filament Max Temp must be greater than 150");
                    return false;
                  } else {
                    return true;
                  }
              - lambda: |-
                  if (id(filament_type).state == "") {
                    ESP_LOGE("main", "Filament Type cannot be empty");
                    return false;
                  } else {
                    return true;
                  }
              - lambda: |-
                  if (id(filament_type).state == "") {
                    ESP_LOGE("main", "Filament Type cannot be empty");
                    return false;
                  } else {
                    return true;
                  }
              - lambda: |-
                  if (id(bambu_serial_number).state == "") {
                    ESP_LOGE("main", "Bambu Serial Number cannot be empty");
                    return false;
                  } else {
                    return true;
                  }
                # TODO: Check if mqtt is enabled once this is merged: https://github.com/esphome/esphome/pull/7716
          then:
            - mqtt.publish:
                # topic: device/${bambu_serial_number}/request
                topic: !lambda 'return "device/" + id(bambu_serial_number).state + "/request";'
                payload: !lambda "auto data = json::build_json([=](JsonObject root) {\n  auto print = root[\"print\"].to<JsonObject>();\n  print[\"sequence_id\"] = \"0\";\n  print[\"command\"] = \"ams_filament_setting\";\n  print[\"ams_id\"] = 255; //TODO: support multiple AMS\n  print[\"tray_id\"] = 254; //TODO: support multiple trays\n  if (id(filament_include_alpha).state == true){\n    print[\"tray_color\"] = id(filament_color_hexaa).state;\n  }\n  else{\n    std::string color = id(filament_color_hex).state + \"FF\";\n    print[\"tray_color\"] = color;\n  } \n  print[\"nozzle_temp_min\"] = uint16_t(id(filament_min_temp).state);\n  print[\"nozzle_temp_max\"] = uint16_t(id(filament_max_temp).state);\n  print[\"tray_type\"] = id(filament_type).state.c_str();\n  print[\"setting_id\"] = \"\";\n  print[\"tray_info_idx\"] = id(filament_brand_code).state.c_str();\n  print[\"tray_type\"] = id(filament_type).state.c_str();\n  //print[\"tray_sub_brands\"] = \"TPU\"; //TODO: support sub brands\n    #magic___^_^___line\n});\nESP_LOGI(\"main\", \"Publishing %s\", data.c_str());\nreturn data;"
  - id: generate_filament_brand_code # TODO: Replace with filament_mappings()
    then:
      - lambda: "id(filament_sub_brand).publish_state(\"\");\n// TPU\nif (id(filament_type).state == \"TPU\") {\n  if (id(filament_brand).state == \"Bambu\") {\n    id(filament_brand_code).publish_state(\"GFU01\");\n    id(filament_sub_brand).publish_state(\"TPU 95A\");\n  } else { // Generic\n    id(filament_brand_code).publish_state(\"GFU99\");\n    id(filament_sub_brand).publish_state(\"TPU\");\n  }\n}\n// PLA\nelse if (id(filament_type).state == \"PLA\") {\n  if (id(filament_brand).state == \"PolyTerra\") {\n    id(filament_brand_code).publish_state(\"GFL01\");\n    id(filament_sub_brand).publish_state(\"PolyTerra PLA\");\n  } else if (id(filament_brand).state == \"PolyLite\") {\n    id(filament_brand_code).publish_state(\"GFL00\");\n    id(filament_sub_brand).publish_state(\"PolyLite PLA\");\n  } else if (id(filament_brand).state == \"Sunlu\") {\n    id(filament_brand_code).publish_state(\"GFSNL03\"); \n  } else if (id(filament_brand).state == \"Bambu\") {\n    // Check for Bambu PLA variants\n    if (id(filament_variant).state == \"Basic\") {\n      id(filament_brand_code).publish_state(\"GFA00\");\n      id(filament_sub_brand).publish_state(\"PLA Basic\");\n    } else if (id(filament_variant).state == \"Matte\") {\n      id(filament_brand_code).publish_state(\"GFA01\");\n      id(filament_sub_brand).publish_state(\"PLA Matte\");\n    } else if (id(filament_variant).state == \"Metal\") {\n      id(filament_brand_code).publish_state(\"GFA02\");\n      id(filament_sub_brand).publish_state(\"PLA Metal\");\n    } else if (id(filament_variant).state == \"Impact\") {\n      id(filament_brand_code).publish_state(\"GFA03\");\n      id(filament_sub_brand).publish_state(\"PLA Impact\");\n    } else { // Default to Basic if no variant specified\n      id(filament_brand_code).publish_state(\"GFA00\");\n      id(filament_sub_brand).publish_state(\"PLA Basic\");\n    }\n  } else { // Generic\n    id(filament_brand_code).publish_state(\"GFL99\");\n    id(filament_sub_brand).publish_state(\"PLA\");\n  }\n}\n// PETG\nelse if (id(filament_type).state == \"PETG\") {\n  if (id(filament_brand).state == \"Overture\") {\n    // TODO: find overture PETG brand code\n    id(filament_brand_code).publish_state(\"GFG99\"); // Using generic for now\n    id(filament_sub_brand).publish_state(\"PETG\");\n  } else if (id(filament_brand).state == \"Sunlu\") {\n    id(filament_brand_code).publish_state(\"GFSNL08\");  \n  } else { // Generic\n    id(filament_brand_code).publish_state(\"GFG99\");\n    id(filament_sub_brand).publish_state(\"PETG\");\n  }\n}\n// PET-CF\nelse if (id(filament_type).state == \"PET-CF\") {\n  if (id(filament_brand).state == \"Bambu\") {\n    id(filament_brand_code).publish_state(\"GFT00\");\n    id(filament_sub_brand).publish_state(\"PET-CF\");\n  } else { // Generic - Note: Using PETG generic as there's no specific PET-CF generic code\n    id(filament_brand_code).publish_state(\"GFG99\");\n    id(filament_sub_brand).publish_state(\"PET-CF\");\n  }\n}\n// ASA\nelse if (id(filament_type).state == \"ASA\") {\n  // Generic\n  id(filament_brand_code).publish_state(\"GFB98\");\n  id(filament_sub_brand).publish_state(\"ASA\");\n}\n// ABS\nelse if (id(filament_type).state == \"ABS\") {\n  if (id(filament_brand).state == \"Bambu\") {\n    id(filament_brand_code).publish_state(\"GFB00\");\n    id(filament_sub_brand).publish_state(\"ABS\");\n  } else { // Generic\n    id(filament_brand_code).publish_state(\"GFB99\");\n    id(filament_sub_brand).publish_state(\"ABS\");\n  }\n}\n// PC\nelse if (id(filament_type).state == \"PC\") {\n  if (id(filament_brand).state == \"Bambu\") {\n    id(filament_brand_code).publish_state(\"GFC00\");\n    id(filament_sub_brand).publish_state(\"PC\");\n  } else { // Generic\n    id(filament_brand_code).publish_state(\"GFC99\");\n    id(filament_sub_brand).publish_state(\"PC\");\n  }\n}\n// PA\nelse if (id(filament_type).state == \"PA\") {\n  // Generic\n  id(filament_brand_code).publish_state(\"GFN99\");\n  id(filament_sub_brand).publish_state(\"PA\");\n}\n// PA-CF\nelse if (id(filament_type).state == \"PA-CF\") {\n  if (id(filament_brand).state == \"Bambu\") {\n    id(filament_brand_code).publish_state(\"GFN03\");\n    id(filament_sub_brand).publish_state(\"PA-CF\");\n  } else { // Generic\n    id(filament_brand_code).publish_state(\"GFN98\");\n    id(filament_sub_brand).publish_state(\"PA-CF\");\n  }\n}\n// PLA-CF\nelse if (id(filament_type).state == \"PLA-CF\") {\n  // Generic\n  id(filament_brand_code).publish_state(\"GFL98\");\n  id(filament_sub_brand).publish_state(\"PLA-CF\");\n}\n// PVA\nelse if (id(filament_type).state == \"PVA\") {\n  // Generic\n  id(filament_brand_code).publish_state(\"GFS99\");\n  id(filament_sub_brand).publish_state(\"PVA\");\n}\n// Support Materials\nelse if (id(filament_type).state == \"Support\") {\n  if (id(filament_variant).state == \"G\") {\n    id(filament_brand_code).publish_state(\"GFS01\");\n    id(filament_sub_brand).publish_state(\"Support G\");\n  } else if (id(filament_variant).state == \"W\") {\n    id(filament_brand_code).publish_state(\"GFS00\");\n    id(filament_sub_brand).publish_state(\"Support W\");\n  } else { // Default to Support W if no variant specified\n    id(filament_brand_code).publish_state(\"GFS00\");\n    id(filament_sub_brand).publish_state(\"Support W\");\n  }\n}\nelse {\n  ESP_LOGE(\"main\", \"Unknown filament type: %s\", id(filament_type).state.c_str());\n}"
  - id: generate_filament_temperatures
    then:
      - if:
          condition:
            and:
              - lambda: |-
                  if (id(filament_type).state == "") {
                    ESP_LOGD("main", "skipping generate_filament_temperatures because filament_type is emptry");
                    return false;
                  } else {
                    return true;
                  }
          then:
            - lambda: |-
                //TODO: add filament_variant temperatures
                if (id(filament_type).state == "TPU") {
                  if (id(filament_brand).state == "Generic") {
                    id(filament_min_temp).publish_state(200);
                    id(filament_max_temp).publish_state(250);
                  } else {
                    ESP_LOGW("main", "Unknown temperatures for TPU: %s", id(filament_brand).state.c_str());
                    id(filament_min_temp).publish_state(200);
                    id(filament_max_temp).publish_state(250);
                  }
                }
                else if (id(filament_type).state == "PLA") {
                  if (id(filament_brand).state == "Generic") {
                    id(filament_min_temp).publish_state(190);
                    id(filament_max_temp).publish_state(240);
                  } else {
                    ESP_LOGW("main", "Unknown temperatures for PLA: %s", id(filament_brand).state.c_str());
                    id(filament_min_temp).publish_state(190);
                    id(filament_max_temp).publish_state(240);
                  }
                }
                else if (id(filament_type).state == "PETG") {
                  if (id(filament_brand).state == "Generic") {
                    id(filament_min_temp).publish_state(220);
                    id(filament_max_temp).publish_state(270);
                  } else {
                    ESP_LOGW("main", "Unknown temperatures for PETG: %s", id(filament_brand).state.c_str());
                    id(filament_min_temp).publish_state(220);
                    id(filament_max_temp).publish_state(270);
                  }
                }
                else if (id(filament_type).state == "ASA") {
                  if (id(filament_brand).state == "Generic") {
                    //TODO: find temps for ASA
                  } else {
                    ESP_LOGW("main", "Unknown temperatures for ASA: %s", id(filament_brand).state.c_str());
                  }
                }
                else if (id(filament_type).state == "ABS") {
                  if (id(filament_brand).state == "Generic") {
                    id(filament_min_temp).publish_state(240);
                    id(filament_max_temp).publish_state(280);
                  } else {
                    ESP_LOGW("main", "Unknown temperatures for ABS: %s", id(filament_brand).state.c_str());
                  }
                }
                else if (id(filament_type).state == "PVA") {
                  if (id(filament_brand).state == "Generic") {
                    id(filament_min_temp).publish_state(190);
                    id(filament_max_temp).publish_state(240);
                  } else {
                    ESP_LOGW("main", "Unknown temperatures for PVA: %s", id(filament_brand).state.c_str());
                    id(filament_min_temp).publish_state(190);
                    id(filament_max_temp).publish_state(240);
                  }
                }
                else if (id(filament_type).state == "PA-CF") {
                  if (id(filament_brand).state == "Generic") {
                    id(filament_min_temp).publish_state(190);
                    id(filament_max_temp).publish_state(240);
                  } else {
                    ESP_LOGW("main", "Unknown temperatures for PA-CF: %s", id(filament_brand).state.c_str());
                    id(filament_min_temp).publish_state(190);
                    id(filament_max_temp).publish_state(240);
                  }
                }
                else if (id(filament_type).state == "PC") {
                  if (id(filament_brand).state == "Generic") {
                    //TODO: find temps for PC
                  } else {
                    ESP_LOGW("main", "Unknown temperatures for PC: %s", id(filament_brand).state.c_str());
                  }
                }
                else if (id(filament_type).state == "PA") {
                  if (id(filament_brand).state == "Generic") {
                    id(filament_min_temp).publish_state(190);
                    id(filament_max_temp).publish_state(240);
                  } else {
                    ESP_LOGW("main", "Unknown temperatures for PA: %s", id(filament_brand).state.c_str());
                    id(filament_min_temp).publish_state(190);
                    id(filament_max_temp).publish_state(240);
                  }
                }
                else {
                  ESP_LOGW("main", "Unknown filament type: %s", id(filament_type).state.c_str());
                }

esphome:
  includes:
    - bambu.h

binary_sensor:
  - id: rfid_reader_spi_0_tag_parsed
    platform: template
    internal: true
    state_topic:
  - id: rfid_reader_spi_0_tag_is_openspool
    platform: template
    internal: true
    state_topic:
