---
substitutions:
  spi_data_rate: 200kHz
  # spi_data_rate: 1Mhz #TODO: decrease this to increase reliability for long cable runs
  # update_interval: "500ms"
  # update_interval: "2s"
  # update_interval: "1s"
  # update_interval: "1500ms"
  update_interval: "750ms"
binary_sensor:
  - platform: template
    name: "NFC Tag Present"
    id: nfc_tag_present0
    state_topic:
    icon: mdi:circle-double
    web_server:
      sorting_group_id: sorting_group_rfid
spi:
  # On esp32-s3 SPI2 a can support 6 devices, whereas only 3 on bus SPI3
  - id: SPI2
    clk_pin: ${spi2_clk_pin} # SCK
    miso_pin: ${spi2_miso_pin} # MO/SDA/TX (MISO)
    mosi_pin: ${spi2_mosi_pin} # M (MOSI)
    interface: ${spi2_type}
pn532_spi:
  - id: rfid_reader_spi_0
    cs_pin: ${rfid0_ss_pin} # NSS/SCL/RX
    spi_id: ${rfid0_spi_interface}
    data_rate: ${spi_data_rate}
    update_interval: ${update_interval}
    on_tag_removed:
      then:
        - script.execute:
            id: set_led_white
            led_number: 0
        - binary_sensor.template.publish:
            id: nfc_tag_present0
            state: OFF
        - lambda: |-
            id(filament_raw_data0).publish_state("");
    on_tag:
      then:
        - binary_sensor.template.publish:
            id: nfc_tag_present0
            state: ON
        - lambda: |-
            bool is_valid_openspool = false;
            std::string payload;

            if (tag.has_ndef_message()) {
              auto records = tag.get_ndef_message()->get_records();
              bool found_json = false;

              // Look for application/json record
              for (const auto& record : records) {
                if (record->get_type() == "application/json") {
                  if (found_json) {
                    // More than one JSON record found
                    ESP_LOGW("NFC", "Multiple JSON records found, using first one");
                    break;
                  }

                  payload = record->get_payload();
                  ESP_LOGD("NFC", "Payload: %s", payload.c_str());
                  id(filament_raw_data0).publish_state(payload);

                  // Parse JSON and check for OpenSpool protocol
                  auto parse_result = json::parse_json(payload, [&](JsonObject root) {
                    is_valid_openspool = root["protocol"] == "openspool";
                    return true;
                  });

                  if (!parse_result) {
                    ESP_LOGE("NFC", "Failed to parse JSON payload");
                  }

                  found_json = true;
                }
              }

              if (!found_json) {
                ESP_LOGW("NFC", "No application/json record found");
              }
            } else {
              ESP_LOGI("NFC", "Tag found without NDEF message");
            }

            // Update states
            id(rfid_reader_spi_0_tag_parsed).publish_state(true);
            id(rfid_reader_spi_0_tag_is_openspool).publish_state(is_valid_openspool);

            // Set LED color
            if (is_valid_openspool) {
              id(set_led_green).execute(0);
              //TODO: Generate and send MQTT message here
              if (!payload.empty()) {
              }
            } else {
              id(set_led_red).execute(0);
            }
        - if:
            condition:
              and:
                - mqtt.connected
                - lambda: 'return id(filament_raw_data0).state != "";'
                - lambda: 'return id(filament_raw_data0).state != "{}";'
                - binary_sensor.is_on: rfid_reader_spi_0_tag_is_openspool
                - binary_sensor.is_on: rfid_reader_spi_0_tag_parsed
            then:
              - mqtt.publish:
                  topic: !lambda 'return "device/" + id(bambu_serial_number).state + "/request";'
                  # 255 = external ams, TODO: A1,P1,X1 might use different values for AMS
                  # 254 = external tray, first filament slot is tray 0
                  payload: !lambda "return bambulabs::generate_mqtt_payload( id(filament_raw_data0).state, 255, 254 );"
text_sensor:
  - platform: template
    name: "NFC Raw Data"
    id: filament_raw_data0
    state_topic:
    internal: false # Always show raw data 0
    icon: mdi:nfc-variant
    web_server:
      sorting_group_id: sorting_group_rfid
    filters:
      - lambda: "auto pretty_json = [](const std::string &x) -> std::string {\n  if (x.empty()) {\n    ESP_LOGD(\"NFC\", \"Input string is empty\");\n    return x;\n  }     \n  ESP_LOGD(\"NFC\", \"Input string: %s\", x.c_str());\n          #magic___^_^___line\n  JsonDocument doc;\n  DeserializationError error = deserializeJson(doc, x);\n  if (error) {\n    ESP_LOGE(\"NFC\", \"JSON parsing failed: %s\", error.c_str());\n    return \"\";\n  }\n          #magic___^_^___line\n  if (!doc.is<JsonObject>()) {\n    ESP_LOGE(\"NFC\", \"Invalid JSON: Not an object\");\n    return \"\";\n  }\n          #magic___^_^___line\n  const char* required_fields[] = {\"protocol\", \"color_hex\", \"type\", \"min_temp\", \"max_temp\", \"brand\"};\n  for (const char* field : required_fields) {\n    if (!doc[field].is<const char*>() && !doc[field].is<int>() && !doc[field].is<float>()) {\n      ESP_LOGE(\"NFC\", \"Invalid JSON: Missing required field '%s'\", field);\n      return \"\";\n    }\n  }\n          #magic___^_^___line\n  std::string output;\n  serializeJsonPretty(doc, output);\n          #magic___^_^___line\n  if (output.length() > 1024) {\n    ESP_LOGE(\"NFC\", \"Prettified JSON exceeds 1024 bytes\");\n    return \"\";\n  }\n          #magic___^_^___line\n  return output;\n};\nreturn pretty_json(x);\n          #magic___^_^___line"
  - platform: template
    name: "NFC Preview"
    id: nfc_preview
    state_topic:
    icon: mdi:nfc-search-variant
    web_server:
      sorting_group_id: sorting_group_rfid
# Create virtual button that can be pressed in the gui
button:
  - platform: template
    name: "Write NFC"
    id: write_nfc
    state_topic:
    icon: mdi:nfc-tap
    web_server:
      sorting_group_id: sorting_group_filament_settings
      sorting_weight: 210
    on_press:
      then:
        - if:
            condition:
              and:
                # - lambda: |- #TODO: I'm not sure that tag_present registers on blank tags
                #     if (!id(nfc_tag_present0).state) {
                #       ESP_LOGE("main", "NFC Tag not present on RFID Reader 0");
                #       return false;
                #     } else {
                #       return true;
                #     }
                - lambda: |-
                    if (id(filament_brand).state == "") {
                      ESP_LOGE("main", "Filament Brand cannot be empty");
                      return false;
                    } else {
                      return true;
                    }
                - lambda: |-
                    if (id(filament_brand_code).state == "") {
                      ESP_LOGE("main", "Filament Brand Code cannot be empty");
                      return false;
                    } else {
                      return true;
                    }
                - lambda: |-
                    if (id(filament_color_hex).state == "") {
                      ESP_LOGE("main", "Filament Color Hex cannot be empty");
                      return false;
                    } else {
                      return true;
                    }
                - lambda: |-
                    if (id(filament_max_temp).state >= 300) {
                      ESP_LOGE("main", "Filament Min Temp must be less than 300");
                      return false;
                    } else {
                      return true;
                    }
                - lambda: |-
                    if (id(filament_min_temp).state <= 150) {
                      ESP_LOGE("main", "Filament Max Temp must be greater than 150");
                      return false;
                    } else {
                      return true;
                    }
                - lambda: |-
                    if (id(filament_type).state == "") {
                      ESP_LOGE("main", "Filament Type cannot be empty");
                      return false;
                    } else {
                      return true;
                    }
            then:
              - lambda: "auto message = new nfc::NdefMessage();\n    #magic___^_^___line\n//TODO: uncomment once esphome suppports messages nless than 255 bytes\n// URI NDEF record\n// esphome fails if this is more than 255 bytes\n//auto uri_record = std::make_unique<nfc::NdefRecordUri>();\n//std::string url = \"https://openspool.io/tag?\";\n//url.append(\"protocol=\").append(\"openspool\");\n//url.append(\"&version=\").append(\"1.0\");\n//url.append(\"&color_hex=\").append(id(filament_color_hex).state);\n//url.append(\"&type=\").append(id(filament_type).state);\n//url.append(\"&min_temp=\").append(std::to_string(static_cast<uint16_t>(id(filament_min_temp).state)));\n//url.append(\"&max_temp=\").append(std::to_string(static_cast<uint16_t>(id(filament_max_temp).state)));\n//url.append(\"&brand=\").append(id(filament_brand).state);\n    #magic___^_^___line\n// Warn if the url is more than 255 bytes\n// While NFC allows messages longer than 255, you have to set the tnf_byte which esphome doesn't allow yet\n//if (url.length() > 255) {\n//  ESP_LOGE(\"NFC\", \"URL longer than 255 bytes: %s\", url.c_str());\n//  return;\n//}\n//ESP_LOGD(\"NFC\", \"Adding NDEF Record URI: %s\", url.c_str());\n//message->add_uri_record(url);\n    #magic___^_^___line\n// Application/Json NDEF record\nauto json_record = std::make_unique<nfc::NdefRecord>();\njson_record->set_tnf(nfc::TNF_MIME_MEDIA);\njson_record->set_type(\"application/json\");\n    #magic___^_^___line\nJsonDocument doc;\nJsonObject root = doc.to<JsonObject>();\nroot[\"version\"] = \"1.0\";\nroot[\"protocol\"] = \"openspool\";\nif (id(filament_include_alpha).state == true){\n  root[\"color_hex\"] = id(filament_color_hexaa).state;\n}\nelse{\n  root[\"color_hex\"] = id(filament_color_hex).state;\n} \nroot[\"type\"] = id(filament_type).state;\nroot[\"min_temp\"] = id(filament_min_temp).state;\nroot[\"max_temp\"] = id(filament_max_temp).state;\nroot[\"brand\"] = id(filament_brand).state;\n    #magic___^_^___line\nstd::string json_string;\nserializeJson(root, json_string);\nif (json_string.empty()) {\n  ESP_LOGE(\"rfid\", \"Failed to serialize JSON\");\n  return;\n}\nESP_LOGI(\"rfid\", \"JSON content to be written: %s\", json_string.c_str());\njson_record->set_payload(json_string);\nmessage->add_record(std::move(json_record));\n    #magic___^_^___line\nstd::vector<uint8_t> encoded_message = message->encode();\nsize_t message_size = encoded_message.size();\nESP_LOGI(\"rfid\", \"NDEF message size: %zu bytes\", message_size);\n    #magic___^_^___line\n// TODO: make dynamic for NTAG215 (544) or NTAG216 (888)\n// TODO: 544 bytes is actuall 496 usable according to logs\n//const size_t MAX_MESSAGE_SIZE = 496;\n//if (message_size > MAX_MESSAGE_SIZE) {\n//    ESP_LOGE(\"rfid\", \"Error: NDEF message size (%zu bytes) exceeds maximum allowed size (%zu bytes)\", message_size, MAX_MESSAGE_SIZE);\n    //return;  // Exit the function or throw an exception, depending on your error handling strategy\n//}\n    #magic___^_^___line\nid(rfid_reader_spi_0).write_mode(message);\nESP_LOGI(\"rfid\", \"Writing JSON NDEF message to tag\");"
              - wait_until:
                  not:
                    pn532.is_writing:
                      id: rfid_reader_spi_0
              - logger.log:
                  tag: "rfid"
                  format: "Finished writing tag"
                  level: INFO
              - lambda: |-
                  id(set_led_green).execute(0);
            else:
              - lambda: |-
                  ESP_LOGI("rfid", "NFC Tag not present");
